{%- let inner_ffi_converter = inner_type|ffi_converter_name %}

// Generated by OptionalTemplate
class {{ ffi_converter_name }} extends _UniffiConverterRustBuffer {
    //static {{ type_name }} lift(_UniffiRustBuffer buf) {
    static {{ type_name }} lift(buf) {
      if (buf.len > 0) {
        buf.data = Pointer.fromAddress(buf.data.address + 0x5);
        return {{ inner_ffi_converter }}.lift(buf);
      } else {
        return null;
      }
    }

    //static _UniffiRustBuffer lower({{type_name}} buf) {
    @override
    _UniffiRustBuffer lower(buf) {
      if (buf == null) {
        return {{ inner_ffi_converter }}().lower("\u{0}");
      } else {
        return {{ inner_ffi_converter }}().lower("\u{1}" + buf);
      }
    }
}
