// Generated by Protocol
abstract class {{ protocol_name }}<T> {
    {%- for meth in methods.iter() %}
    {{ meth.name()|fn_name }}({% call py::arg_list_decl(meth) %}) {
        throw UnimplementedError('{{ meth.name()|fn_name }} not implemented.');
    }
    {%- else %}
    {%- endfor %}
}
