{%- let rec = ci|get_record_definition(name) %}
// Generated By RecordTemplate: 1
class {{ type_name }} {
    {% for field in rec.fields() %}
        static {{ field|type_name }} {{ field.name()|var_name }};
    {%- endfor %}

    {{ type_name }}({ {% for field in rec.fields() %}
    {%- if field.default_value().is_some() %}
      required this.{{ field.name()|var_name }}/* = _DEFAULT*/
    {% else %}
      required this.{{ field.name()|var_name }}
    {% endif %}
    {%- if !loop.last %}, {% endif %}
    {%- endfor %} }); 

    @override
    String toString() {
        return "{{ type_name }}({% for field in rec.fields() %}{{ field.name()|var_name }}={}{% if loop.last %}{% else %}, {% endif %}{% endfor %})".format({% for field in rec.fields() %}self.{{ field.name()|var_name }}{% if loop.last %}{% else %}, {% endif %}{% endfor %})
    }

    __eq__(other) {
        {%- for field in rec.fields() %}
        if self.{{ field.name()|var_name }} != other.{{ field.name()|var_name }}:
            return False
        {%- endfor %}
        return True
    }
}

// Generated By RecordTemplate: 2
class {{ ffi_converter_name }} extends _UniffiConverterRustBuffer {
    static read(buf) {
        //return {{ type_name }}(
        //    {%- for field in rec.fields() %}
        //    {{ field.name()|var_name }}={{ field|read_fn }}(buf),
        //    {%- endfor %}
        //)
    }

    static write(value, buf) {
        {%- for field in rec.fields() %}
        //{{ field|write_fn }}(value.{{ field.name()|var_name }}, buf)
        {%- endfor %}
    }
}
