{%- let inner_ffi_converter = inner_type|ffi_converter_name %}

// Generated by SequenceTemplate
class {{ ffi_converter_name}} extends _UniffiConverterRustBuffer {

    static lift(buf){
    }

    static lower(buf){
    }
}
