{%- let inner_ffi_converter = inner_type|ffi_converter_name %}

// Generated by SequenceTemplate
class {{ ffi_converter_name}} extends _UniffiConverterRustBuffer {
    static write(value, buf) {
        //items = len(value)
        //buf.write_i32(items)
        //for item in value:
        //    {{ inner_ffi_converter }}.write(item, buf)
     }

    static read(buf){
        //count = buf.read_i32()
        //if count < 0:
        //    raise InternalError("Unexpected negative sequence length")

        //return [
        //    {{ inner_ffi_converter }}.read(buf) for i in range(count)
        //]
    }

    static lift(buf){
    }

    static lower(buf){
    }
}
